#!/bin/bash

# Проверьте, запущен ли скрипт от root
if [[ $EUID -ne 0 ]]; then
   echo "Этот скрипт должен быть запущен от root" 
   exit 1
fi

apt install sudo
# Массив с именами пользователей и их SSH ключами
declare -A users
users=(
#    ["erasyl"]="Erasyl Akimjanov:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCvGaImqyt6zE3WAEvGXvJ/zVLJjM75ZW8jtHUuVN7t+eVJMya4e+ctx3P7/DPS6LjKL5zdZyExqbk9WAR7keiAYoCS9rJ+4r2EEtdy7XhCPekLR3DWErHy3eeMxU18Dt8XhZfqIAEC4Irv6jDQ9FBv3Xl8k5/o/Ftp42euB5BVdYn+NgMDSnJ1Rf8+ZnzDQLMuh9pyNx5iCu11ZHLoWd5TPZ+jEqvQluJM8s2VEuptyPqbyeJ5miobBkMyfuGkM4vwhMGkEaB/4b+d6MK/nmhcIc3XOhpkuy4nd0YA1lCkQDDQbY6PeCkVZwGdOS82s668SWMv3DUpWRTnJxEKdKEAMFeaqstpLDDWeiOaiNWpk31Jb7kNsTBdJ5NIfQFZ/Zx2DtJJSaX/UsC74hQmIPCyH/Ys8GdZDfR79FPwNjP/wcePaZhkEecTadyXsfItQJN/SpuyBQveBBgYlTAPOn3tr79S3zsiXcAcT0MaNDmMpInvML6kHBSCKX+blJiIN6DP4mN/nwyww4flQeOGeyf1mPEQBUvtyQxUu+wPlTVt2hDT0tPrn802Q4POcxoRBnmB+61OlmxQ5HTkpGz7hQZQ4+0oG1TK3VEf5XIeQaLcNpMOh1q2rmMUIfId2JQn3r0Gn5nc6cuxoYuvCqtbAQlNtbEElvKzBd20vmHJljh/iQ== asyl@up"
#    ["bektur"]="Bektur Razzakov:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDRJJ8DLKhdy9SXl61PUNd0xTl21ah+TqFE+dBOiIbZauJx1qz6T3fUg8QXPsvvjVAxYuMDh3T2LQfFRlzM+r/04+y8EeiWbNNqAPkgBInmR/29brrgfETSYMnHdtW2sdT/D+/6wV9IHXevKZaQ/3K4FZAbhjqdYAkNDRX74IVTWRVw8a0T1kxEvejEd59JTo2AqYGCpYPd1idMOiLVuNYAHTH6elGxQvx0aExRPHRj2ASmG1gbwIYlPc3OYJ0CIxSgqoWyskl08kb6x0ivbHJ0BGXAMs3fBNSyg+MxHdjJCghKnDtkID7ip4VuwNGJUVCmrQFbMIz2GMRuNAwuPDEZhXh+NWuCiclr77bE0pV7lBgcxm6miIuaW3p6pNSHSNx/bTBEIbVHIO5U2JrmC2J1CVcqSv/7FsK0ngO4eTtHvbfeYEPgzLYFPM8YUUHR5wngZjeyGnHMQrrbABOB7Upb0csYQuHj+2M1Lach44uHUjBea0wnfvwAXyum9tApVJbuc2jAaTebIMrMi+4kYWTArxIT1Yru3SmMZ98dvpDE695cAM8ZfiEKIzf7Jl17MKub0LAzSlAGqLgvYoaeTQT0Bj3SPXrzDziHkaF/5wnFyitPqUB4pSp4v9ZitxwberomsDtj3kceaqqVibACbe1bZWhYGpKQls+e8yv1dcH37w== brzzkv@gmail.com"
#    ["artur"]="Artur Kuliev:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsc8Sa2YahuXcCnFYQnFJw90QzTHig7OIGjVsm0wRfXDqlXxJz01ohJjM966EBEDPylz+JyUjxJOc6rY5FUh/egcM4sxmOuQdfy2U1ZuMfIfu2zmBO9+52N2MgjGPpFRqGM3doiYYtEqEun+6mQ7e1gBJey9V8EFsTlFz0hLGq9bineXzgVbahDFfK3sgWKjdE4zVJvMRSoVRT+YlZFegq4aYlK8AWW7d8EG2U75vPqHay5elKRNx6vQW8OBfmawsDjh+azdwppY0v2IvLBF8RaSzvDMbjASSUn8m4StOyicQNB5ZItTFrd/lfb6FdrgyznzC8fyDMssTbgn5bGYcr Generated By Termius"
#    ["ilim"]="Ilim Irgashev:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCbnZNCpBqSRFgkN3G/kIHmNDJ7Xeaoct2ENtia4MbFaAwdmzHzhwwBa5shK/feeUKYpRZ3IRh6vbeG3jKVhTUhMW6xP1k1nStRbP+tyvvSusnGs17gB4j5CYuzGpjufopYL9FC8wcGtekytjMC/AdyhzgzBSZk74h0BUIy/fWWk0Aj+/puhxZPNhyWBHml2gcDF5VhLnhwslB5wDeDam30THEJFUogJuDna6up2blyYT0eDbBN7oJcYmmql4DwJ7yIxoe4RSZ6WONTJR6mP+GLeJR9m/HiEYiPzkxh4bRlTw4OduFp9WCJGQquqUbjfJ88qMBYMKWksYdTnClW6Cv9EEQTB9Ho1J0dcKtwA4wNxHmuKQyHsR3oBJV0ghUCSLDkk1VuvGb89eE6/+9Jx6YFsPh3yEu4cvV344LzX5rVK5tF09vlmf9D0pkXPx2756MvCTiGps3LZQXv2fG+mRQkao550zUDDOnOIn2cCofBUdIqAbFT77E/80h4xcVBnbgfA0NomJ2U65pBSeLIAhZ++IDdOcDekxHXznspniWsLmhaB/jRdD8B5LVMex9KI5SHMllYjkvlp5QuJpjLkP3OV+B7Kr6P7PWhDV8nBd5PYRdg/XcJe+vlBCWWlljtJ8roRanbaumT0GRDqTauNdhhcmHRsnlgb2FO3P9Hi4vFGQ== ilimirgashev@gmail.com"
#    ["vlad"]="Vladislav Filushko:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCfK0COpW3fxNF7yBrolBuN61AjZH0Is7YaB8qfZaKACKuZMNk/F0qnamod9U1yL5bsxBYPv0Yup1DdPzKypI9At+yhILDk/WofCtLOkOPtPXOAzSf9a1VWZWRjmx63sjW9vrS1P02Ut1qAc7KHeiY56RfrOsfzjIEaxrwcWt+WtryueureCgGeoRs2u6YZI/TVCnJzlnYwFf3VvNq9ybWRVG+F7HhTSz17zxde9EKEkUs3+UVFsHu6WguFWe0/MkbRYjkJ81ZtChpomUwoFRlgvxHEo90YbE4CKzBuO2F++S1EOBHyrQat8Dzzo/YxGz+O78cbaWbW1/8uUILzWKCLbvf1UGqeK2DThWDfpfj7fLPRKGAm81coyM0e5HEAHT2LkuxP2mp15Pugdyo1agkHY/o7696M9dNJAHxpoeVJPedhSuThWGLqKg1lCFwAYyb2oKVq7LanJSWwO91eimkMrgOX1Kq1zwGiurwU5F7ZeMdN+Cuq42T7gcSeQs9hi/dQopem+Dh5+HUI3owVQcRPPbSPbz5xfbBKpYVy5mWzhYf3+3xuaYUkQVG6+uXc98rBCnhYyZoCEhgp6C+a3fAoLVoYNX0cYk5MohJA54FRg5muKfPsfhZ2wR2Ms44H97oYt82rjlySX9OF8cNprW/W6u+vlfu9ZstcvOVnDjUbQw== vladosmen29@gmail.com"
#    ["akyl"]=""
#    ["suhrab"]="Suhrab Usenbaev:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNW346IQLXnhKoem5n6HVqg0lTqnn/+dMKEdPGutinuWYo6vKTAu241LJFBvTAN8h0WJngfnmIdjBwIKE2xq5zFq6Tl6SYTHwIvnT+5GsJcuPWr93UEZv9HqXClNwRTjj4bStoc+khvncn9mb3uv9DYNQFzb+bgl2ifLKqHyXhMCdZksO53i2V2+A/y9ngCpfynItCMdh4lD/+DqYociJ8ALCJtcL63VA2s7u2EB4jVUVUVec7O0sJS7vTAWpr3utOXpHld4jqCpcYsd84xA8MIbz1beh1oOOxvMnqj+u28RqLL5f+4hiPmXJIX8Km2h9k8cHBJvaMKCi6SrpDsw43 Generated By Termius"
#    ["zafar"]="Zafar Usenbaev:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJwn+U4xwUfdj0kChCTm+1Dz8cv3o+BeXUD/1WMF8A4ZRuy7aGUcLfS97RGL0sOLGkgARqZq3jRMFtOu/L2ZBh6dH2yLSSbMFmseS+TPJNLOT7j9bJOBbdWC7+yWcHB9wHyx4Qb0eSg73dijgzxx6Rl4rC9+MY+OpLSnaN21QmC8RRU5D0a77hI0mwJa8p3JUhzdpNz73XER185L5itrVUEJmtMXoO6erdvj/k2nNbaR8f+41hQzYo31lZeOe2sHh5rjDCI6PlQEcUmdtrUqgtTMR7kwBcRoJJkmqpCBwhw1BbmO5SI2CFFQmVpZ5IH2C/4v3upKmIMuNy2+Ggx7ch Generated By Termius"

    ["emil"]="Emilbek Talipov:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDs/745EhTuIj6MQ1GkJKd6ZwfN0+lCR4U1fre6OFotI7rFJ12oztqmy5G81qF6e/KeMSHa9urzxJ8F6f7Sdjf5pjQHvYpryP3dJbzqEOyxiM9ZzUik8htMqdoaKRgjckGv3Ek3u0P6YV+f4UNaNKKkeDqx2YkgnDOpxyNH87IH9NaeQ/px4IB9qlpUZX4XzQXpMOXN+YSXOn3NnIXFhJ9xidfm5i/pSE10h1LUyFO7mTv7t42uKMNG8x3G94qsLMe1t5xESO+ghWqZqzxOhoa+IaXj69Z1kGWqU5kZt7UQBrxzsQaaTrhnOZFqIiL7kJTmKXaU0sHUYwUlbXn9IDrkkaOew0E1k4blxNbktznIgXYPZ5qBU/CysPdkAougFjJivOEy2knq5gi1AfEPjX4iebLRZD0y4uK1quYpzali2I34Nnvdj7PkWCpIOdYvnVkZKOKoQerMMnxN/SUybpA0SxuCAooj4bO62UkcX/gwb0KZR/Ul82ylS4NgLXQcHmgvvz2l2j8FRpApQqgFzYlFEGz7KQy+FuaxjCLGjhdMHBLzd9fCgMHTlSJNcVCM2rSKbMrNRTesJS4LMSuVv836/Bg8KHx6tNsyJw+g2LGQY9KvozfQpsc5V43fWlSC0cnYYgtnUYuAQ7pwuJHOQQBUft+fulXF6JzW763t3b3DLw== Generated By Termius"
    ["isman"]="Islambek Joomartov:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC55gEcQmoQ13hGdl4zmDsg0eL8kSwjfdBgDnveu2fJ3LQfxpwxBSqiGbnAcL/s3OkQth4P7gAIT5L11FxuR4J6KCz3yjoU6EKI9sbu0CdzYf2YzNg5trFLVdTxVQadZA5S9xpsgNgnDrsAs0iOxOpBrNoUw88mqX0kH1OhB7gFuDqCl/4RaGHGsq0KjvdW2MTVNj3o74erFuZ77uovgF/IIZgvjTBqisHdETnG0iealvzVSl4XRNoxljrXaRpQR06qxufqCeGdfohDaPnQmoY54rAE/kDeIkDz6qw1XKVRCnsHVwht45ZieTlIxys3iMKmMBrUMkOjVLObZRXjcSEd Generated By Termius"

)

# Цикл по пользователям
for username in "${!users[@]}"; do
    user_info="${users[$username]}"
    full_name=$(echo "$user_info" | cut -d':' -f1)
    ssh_key=$(echo "$user_info" | cut -d':' -f2)

    # Добавление пользователя с полным именем
    sudo useradd -m -s /bin/bash -c "$full_name" "$username"
    /usr/sbin/adduser $username docker

    # Установка стандартного пароля
    echo "$username":<PASSWD> | sudo chpasswd

    # Добавление пользователя в группу sudo
    sudo usermod -aG sudo "$username"

    # Создание .ssh директории
    mkdir -p /home/"$username"/.ssh

    # Копирование публичного ключа в файл authorized_keys
    echo "$ssh_key" >> /home/"$username"/.ssh/authorized_keys

    # Установка правильных прав
    chown -R "$username":"$username" /home/"$username"/.ssh
    chmod 700 /home/"$username"/.ssh
    chmod 600 /home/"$username"/.ssh/authorized_keys

    # Выводим сообщение о завершении
    echo "Пользователь $username ($full_name) добавлен в группу sudo и SSH ключ добавлен"
done

systemctl restart sshd
# Завершение скрипта
exit 0
